title: Thomas Estabrook
description: None
theme: just-the-docs

url: https://github.com/tgestabrook/tgestabrook.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
